// FAQ hub (Phase 3). 100+ original Q&As. Business facts are VERIFIED (since 1976,
// family-owned, Saluda SC, authorized Bush Hog dealer, carries Great Plains,
// custom blends, bulk/bagged, pickup/delivery); everything else is general
// educational guidance. No pricing, no delivery-radius claims, no chemical rates.
export type Faq = { q: string; a: string };
export type FaqGroup = { title: string; items: Faq[] };

export const FAQ_GROUPS: FaqGroup[] = [
  { title: "Company & trust", items: [
    { q: "How long has Rodgers Fertilizer been in business?", a: "Since 1976 — we're a family-owned and operated business in Saluda, South Carolina." },
    { q: "Are you family-owned?", a: "Yes, family-owned and operated since 1976." },
    { q: "Where are you located?", a: "409 N Main St, Saluda, SC 29138." },
    { q: "What are your hours?", a: "Monday–Friday, 8:00 AM–5:00 PM. Please call to confirm holiday hours." },
    { q: "Are you an authorized Bush Hog dealer?", a: "Yes — we're an authorized Bush Hog dealer for equipment and parts." },
    { q: "Do you carry Great Plains equipment?", a: "Yes, we carry Great Plains equipment in addition to Bush Hog." },
    { q: "Who do you serve?", a: "Commercial farms, pasture and cattle operations, hay producers, hunters and food-plot managers, landscapers, and backyard growers." },
    { q: "Do you only sell to big farms?", a: "No — we help operations of every size, from bulk commercial orders to a single bag for the garden." },
    { q: "How do I contact you?", a: "Call 864-445-2104 (or 800-753-7294), stop by our Saluda store, or send a request through this site." },
    { q: "Can I request a quote online?", a: "Yes — use our quote forms and we'll follow up. A form is a request, not a binding order, and we don't publish prices online." },
  ]},
  { title: "Fertilizer basics", items: [
    { q: "What do the fertilizer numbers mean?", a: "They're the percentage of Nitrogen, Phosphorus, and Potassium (N-P-K) by weight — for example, 10-10-10 is 10% of each." },
    { q: "What does nitrogen do?", a: "Nitrogen drives green, leafy growth." },
    { q: "What does phosphorus do?", a: "Phosphorus supports roots, establishment, and seed and fruit development." },
    { q: "What does potassium do?", a: "Potassium builds overall plant health, stress tolerance, and winter hardiness." },
    { q: "What is 10-10-10 used for?", a: "It's a balanced, all-purpose blend for lawns, gardens, and general pasture feeding." },
    { q: "What is 17-17-17?", a: "A balanced blend like 10-10-10 but more concentrated, so you use fewer pounds for the same nutrients." },
    { q: "What is 0-0-60?", a: "Muriate of potash — 60% potassium, used when a soil test shows you're short on potassium." },
    { q: "Is a higher analysis better?", a: "Not inherently — higher numbers are more concentrated, so you use less. The right choice depends on your soil and crop." },
    { q: "How do I know which blend I need?", a: "A soil test is the best guide; bring it to us and we'll recommend a standard or custom blend." },
    { q: "Do you carry premium fertilizer?", a: "We carry standard blends and a premium 10-10-10 — ask us about the specific formulation." },
    { q: "Can fertilizer be used on lawns and gardens?", a: "Yes — balanced blends like 10-10-10 are common for lawns and gardens; we also carry bagged product for smaller jobs." },
    { q: "How should I store fertilizer?", a: "Keep it dry and sealed, off the ground, and away from moisture so it doesn't cake." },
    { q: "How much fertilizer do I need?", a: "It depends on your area and rate — try our fertilizer calculator, then confirm with a soil test or with us." },
    { q: "Can I over-apply fertilizer?", a: "Yes — over-applying wastes money and can harm plants and water quality. A soil test keeps rates right." },
  ]},
  { title: "Custom blending", items: [
    { q: "Do you do custom fertilizer blends?", a: "Yes — we blend fertilizer to your soil test, crop, and target analysis. It's what we've done since 1976." },
    { q: "Do I need a soil test for a custom blend?", a: "It's the best starting point but not required — we can work from your crop and goals." },
    { q: "What should I tell you for a custom blend?", a: "Your crop or use, acreage, target analysis (or soil test), quantity, packaging, and pickup or delivery." },
    { q: "Is custom blending only for large acreage?", a: "No — custom blends help any grower who wants the right nutrients for their ground." },
    { q: "Can you match my Extension recommendation?", a: "Yes — bring your soil-test recommendation and we'll build a blend to match it." },
    { q: "What packaging can a custom blend come in?", a: "50-lb bags, pallets, one-ton totes, or bulk." },
    { q: "How long does a custom blend take?", a: "Turnaround varies with the season and order — call and we'll give you a realistic timeframe." },
    { q: "Can you blend for food plots?", a: "Yes — we blend for food plots, pasture, hay, gardens, and more." },
  ]},
  { title: "Bulk, packaging & totes", items: [
    { q: "Do you sell bulk fertilizer?", a: "Yes — we blend and load fertilizer in bulk by the ton." },
    { q: "What packaging options are there?", a: "Individual 50-lb bags, pallets, one-ton bags (totes), and bulk." },
    { q: "What is a one-ton tote?", a: "A one-ton bag — bulk quantity with easier handling than loose bulk." },
    { q: "Is bulk cheaper than bags?", a: "Per ton it's usually the most efficient, but factor in handling and spreading — sometimes totes or pallets fit better." },
    { q: "Can I buy a single bag?", a: "Yes — we sell individual 50-lb bags as well as pallets and bulk." },
    { q: "How many bags come on a pallet?", a: "It varies by product — we'll confirm the count on your order." },
    { q: "Do you sell fertilizer by the pallet?", a: "Yes — palletized bagged fertilizer is available for larger jobs." },
    { q: "Is there a minimum order?", a: "Minimums depend on the product and delivery — tell us what you need and we'll confirm." },
    { q: "Can I mix blends on one order?", a: "Often yes — ask us and we'll let you know what works for your quantities." },
    { q: "Do you sell to dealers or resellers?", a: "Ask us — wholesale and dealer supply are handled by our team." },
  ]},
  { title: "Delivery & spreading", items: [
    { q: "Do you deliver?", a: "Yes — we offer delivery as well as customer pickup. Tell us your location and we'll talk through options." },
    { q: "How far do you deliver?", a: "Delivery areas are confirmed with our team — let us know where you are." },
    { q: "How much can you deliver at once?", a: "We reference flatbed delivery up to 24 tons." },
    { q: "Can I pick up instead of delivery?", a: "Absolutely — customer pickup is always available at our Saluda location." },
    { q: "Can you spread the fertilizer for me?", a: "Yes — we offer spreader-truck service, or you can borrow our pull-behind spreaders for your tractor." },
    { q: "Do you spread lime too?", a: "Ask us — we supply agricultural lime and can discuss delivery and spreading." },
    { q: "How is delivery priced?", a: "Delivery is quoted with your order based on product, quantity, and location — we never publish set prices." },
    { q: "What do you need to quote delivery?", a: "The product, quantity, delivery location, and site access, plus your preferred date." },
  ]},
  { title: "Lime & soil", items: [
    { q: "What does lime do?", a: "Lime raises soil pH, correcting acidity so fertilizer nutrients become available to plants." },
    { q: "Do I need lime or fertilizer?", a: "Often both — lime fixes pH, fertilizer feeds the plant. A soil test tells you what you need." },
    { q: "Should I lime or fertilize first?", a: "Correct pH with lime first; if pH is off, fertilizer is far less effective." },
    { q: "How long does lime take to work?", a: "Months — which is why it's applied ahead of the season." },
    { q: "When should I apply lime?", a: "Often in fall, so it has time to raise pH before spring growth." },
    { q: "Do you carry agricultural lime?", a: "Yes — ask us about the lime products currently available and what fits your soil." },
    { q: "How much lime do I need?", a: "Your soil test gives a lime recommendation; our lime calculator helps you estimate the total." },
    { q: "Where do I get a soil test?", a: "Your county Extension office is the usual starting point — bring the results to us for a blend." },
  ]},
  { title: "Seed & food plots", items: [
    { q: "Do you sell seed?", a: "Yes — food-plot and wildlife seed, grass and cover seed, and seasonal seed." },
    { q: "When do you plant ryegrass in SC?", a: "Typically fall — roughly September through November." },
    { q: "What is browntop millet good for?", a: "A fast warm-season grass often planted for dove and quail fields; it grows 2–3 feet tall." },
    { q: "Do you carry food-plot seed?", a: "Yes — seasonal food-plot seed plus the fertilizer and lime to make it produce." },
    { q: "What should I plant for deer?", a: "A mix of cool-season fall plots and warm-season forage — we'll help you plan by season." },
    { q: "When are fall food plots planted?", a: "Late summer into fall for cool-season plantings; lime ahead of time and feed at planting." },
    { q: "Do you carry garden seed?", a: "We carry seasonal seed — ask us what's in stock for the season." },
    { q: "Do you have pasture or cover-crop seed?", a: "Ask us — availability is seasonal and we'll confirm what's on hand." },
    { q: "What fertilizer for food plots?", a: "Match it to your soil test and the seed; we can blend or recommend the right analysis." },
    { q: "Can you help me plan a dove field?", a: "Yes — we'll help you time a fast warm-season planting like millet for your season." },
  ]},
  { title: "Equipment (Bush Hog & Great Plains)", items: [
    { q: "Are you a Bush Hog dealer?", a: "Yes — an authorized Bush Hog dealer for equipment and parts." },
    { q: "What Bush Hog equipment do you carry?", a: "Rotary cutters, hay equipment, and implements — tell us your tractor and job and we'll help you spec it." },
    { q: "What size rotary cutter do I need?", a: "Match the cutter's rated horsepower range to your tractor, then choose width by acreage and material." },
    { q: "What rotary cutter widths are available?", a: "Cutters range roughly 4–6 ft, 7–10 ft, and 12–20 ft (multi-spindle)." },
    { q: "Single or multi-spindle cutter?", a: "Single-spindle suits narrower widths; multi-spindle handles wide widths and heavier material." },
    { q: "Do you carry Great Plains drills?", a: "We carry Great Plains equipment — ask about current availability and configuration." },
    { q: "What is a no-till drill for?", a: "Planting seed into existing residue without full tillage — common for pasture, cover crops, and food plots." },
    { q: "Can you help me match a cutter to my tractor?", a: "Yes — give us your tractor horsepower and what you're cutting and we'll recommend the right machine." },
    { q: "Do you offer financing or used equipment?", a: "Ask us — those options are confirmed with our team." },
    { q: "Do you service equipment?", a: "Contact us and we'll let you know how we can help with your equipment and parts needs." },
  ]},
  { title: "Parts", items: [
    { q: "Do you sell Bush Hog parts?", a: "Yes — blades, gearbox parts, driveline parts, bearings, and wear parts." },
    { q: "I don't know my part number — can you help?", a: "Send your model and a photo of the part and we can usually identify it." },
    { q: "How do I request a part?", a: "Use our Request-a-Part form with your model and part number (photos help), or call us." },
    { q: "Do you ship parts?", a: "Pickup is always available; ask us about shipping options." },
    { q: "Do you carry rotary cutter blades?", a: "Common wear parts are frequently available — send your model and we'll confirm." },
    { q: "How often should I replace cutter blades?", a: "When they're worn, cracked, bent, or badly dull — damaged blades cut poorly and are unsafe." },
    { q: "Can you get parts you don't stock?", a: "Ask us — tell us the model and part and we'll let you know what we can do." },
    { q: "What info do you need for a part?", a: "Manufacturer, model, serial number, part number if known, a description, and a photo." },
  ]},
  { title: "Ordering & visiting", items: [
    { q: "How do I place an order?", a: "Call us, stop by the Saluda store, or send a quote request through this site." },
    { q: "Is a form submission a binding order?", a: "No — online forms are requests. We follow up to confirm details before anything is finalized." },
    { q: "Do you publish prices online?", a: "No — fertilizer, freight, and equipment prices change, so we quote them rather than post them." },
    { q: "Can I reorder a previous blend?", a: "Yes — use Quick Reorder with your prior blend or order reference and we'll confirm." },
    { q: "What payment methods do you take?", a: "Please call — payment options are confirmed with our team." },
    { q: "Can I set up a commercial account?", a: "Ask us about commercial accounts; availability and terms are confirmed by our team." },
    { q: "Do you offer tax-exempt purchasing?", a: "If you're tax-exempt, let us know when you order and we'll handle it appropriately." },
    { q: "How quickly will you respond to a request?", a: "We follow up on requests promptly during business hours — call for anything urgent." },
  ]},
  { title: "Local", items: [
    { q: "Do you serve growers near Newberry?", a: "Yes — Newberry-area growers are part of the community we serve from nearby Saluda." },
    { q: "Do you serve the Greenwood area?", a: "Yes — Greenwood-area growers can reach us in Saluda for blends, bulk, seed, and equipment." },
    { q: "Do you serve the Lexington area?", a: "Yes — we serve growers and landowners connected to the Lexington County area from Saluda." },
    { q: "Are you close to Saluda County farms?", a: "We're located right in Saluda at 409 N Main St, serving Saluda County and the surrounding area." },
    { q: "What crops are common in this area?", a: "Cattle and pasture, hay, poultry, row crops, and peaches are all part of Midlands SC agriculture." },
    { q: "Can I just stop by?", a: "Yes — visit us Monday–Friday, 8–5, at 409 N Main St, Saluda, SC." },
  ]},
];
export const FAQ_COUNT = FAQ_GROUPS.reduce((n, g) => n + g.items.length, 0);
